# See: https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features

github:
  description: "Website sources for the Apache Events website"
  homepage: https://events.apache.org
  labels:
    - apache
    - community
    - comdev
    - events
    - hugo

notifications:
  commits:      commits@community.apache.org
  issues:       dev@community.apache.org
  pullrequests: dev@community.apache.org

# Looks like this may be needed to override the default host name
publish:
  whoami: asf-site
  hostname: events.apache.org

# Test site in preview/sample; output to preview/sample-staging
# autostage will publish the site at community-sample.staged.apache.org
staging:
  profile: ~
  whoami:  asf-staging
  autostage: preview/*
